tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "rjyo/moshi"
tap "sanemat/font"
tap "sqldef/sqldef"
tap "universal-ctags/universal-ctags"
cask "claude-code"
cask "ngrok"
cask "raycast"
brew "anyenv"
brew "azooKey"
brew "colordiff"
brew "fzf"
brew "ghq"
brew "git"
brew "go"
brew "herdr"
brew "jq"
brew "moshi-hook"
brew "neovim"
brew "ngrok"
brew "nkf"
brew "postgresql"
brew "sqldef/sqldef/psqldef"
brew "ripgrep"
brew "source-highlight"
brew "starship"
brew "the_silver_searcher"
brew "tailscale"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew 'yarn', args: ["ignore-dependencies"]
brew "sanemat/font/ricty", args: ["with-powerline"]
