tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "sanemat/font"
brew "anyenv"
brew "fzf"
brew "ghq"
brew "git"
brew "go"
brew "jq"
brew "neovim"
brew "source-highlight"
brew "starship"
brew "the_silver_searcher"
brew "tmux"
brew 'yarn', args: ["ignore-dependencies"]
brew "sanemat/font/ricty", args: ["with-powerline"]
