[[plugins]]
repo = 'Shougo/dein.vim'
rtp = ''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = '''
  let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'cakebaker/scss-syntax.vim'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
  let g:user_emmet_leader_key='<C-T>'
'''

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'
#hook_add = '''
#  let g:indent_guides_enable_on_vim_startup=1
#  let g:indent_guides_guide_size=1
#  let g:indent_guides_auto_colors=0
#  autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#2D3632 ctermbg=black
#  autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#2D3632 ctermbg=black
#'''

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'itchyny/lightline.vim'
